import type { Metadata } from "next";
import { Manrope, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import { ChatProvider } from "./context/chatContext";
import { ThemeProvider } from 'next-themes';
import Image from "next/image";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetBrains = JetBrains_Mono({
  variable: "--font-jetBrains",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${manrope.variable} ${inter.variable} ${jetBrains.variable} h-full antialiased`}
    >
      <head>
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />
      </head>
      <body suppressHydrationWarning className="bg-surface font-body text-on-surface min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ChatProvider>
            <Header />
            {children}
          </ChatProvider>
          <footer className="full-width mt-auto bg-surface-container-low border-t border-outline-variant/10">
            <div className="flex flex-col md:flex-row justify-between items-center w-full px-4 md:px-8 py-6 gap-8">
              <div className="flex flex-col items-center md:items-start gap-1">
                <span className="font-display text-2xl font-bold text-primary">BluEdu</span>
                <p className="font-body text-sm text-on-secondary-container text-center md:text-left">Turning CS Notes into Teaching Videos: An AI-Driven Document-to-Video System​</p>
                <p className="font-body text-sm text-on-secondary-container text-center md:text-left">Elizabethtown College SCARP 2026</p>
              </div>
              <div className="flex flex-wrap justify-center gap-6">
              </div>
              <div className="flex gap-4">
                <Image src='/SCARP_image.png' alt="SCARP logo" width={110} height={110} />
              </div>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
